version: '3'

networks:
  redis-cluster-compose:
    driver: bridge

services:
  redis-node-1:
    image: redis:latest
    ports:
      - 17000:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-1
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    image: redis:latest
    ports:
      - 17001:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-2
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-3:
    image: redis:latest
    ports:
      - 17002:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-3
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-4:
    image: redis:latest
    ports:
      - 17003:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-4
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-5:
    image: redis:latest
    ports:
      - 17004:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-node-6:
    image: redis:latest
    ports:
      - 17005:6379
    networks:
      - redis-cluster-compose
    hostname: redis-node-6
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-cluster-creator:
    image: redis:latest
    networks:
      - redis-cluster-compose
    command: redis-cli -p 6379 --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
